[project]
name = "dora-ai-assistant"
version = "1.0.0"
description = "Dora AI - Voice and Vision Assistant powered by Groq"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [

    # AI
    "groq>=0.31.0",
    "langchain-groq>=0.3.0",

    # UI
    "gradio>=5.38.0",

    # Voice
    "gtts>=2.5.4",
    "elevenlabs>=2.59.0",

    # Environment
    "python-dotenv>=1.1.1"
]
